### ISSUE TITLE
Manually defeated

### ISSUE THREAD

**Issue by Alexxino** [ilkerccom/bitcrackrandomiser#17]
hey @ilkerccom ,

What exactly do you mean with the message at the bottom of your website? 
`Note: 2000000-2050000 (First ~%0.98) ranges and 3FAF000-3FFFFFF (Last ~%0.98) manually defeated in Puzzle 66 pool.`

Does it mean that those ranges have been scanned already therefore we can exclude them ? 

Thanks

**Comment by ilkerccom** [comment]
I marked it as manually scanned as it is very unlikely. However, you can still scan these fields with "includeDefeatedRanges". But I think the private key is not in these ranges.

According to my estimations, no private keys were found, especially in the first 7-8%. (Except for small puzzles). That's why I chose those ranges.
