### ISSUE TITLE
Invalid user token value or wallet address.

### ISSUE THREAD

**Issue by mpgxc** [ilkerccom/bitcrackrandomiser#46]
![image](https://github.com/ilkerccom/bitcrackrandomiser/assets/13613590/bda4d10a-bf4c-4886-b9f9-ec704d0a186a)

Before this error happened, I was able to check my Worker working correctly on btcpuzzle.info. I do not know what happened.

**Comment by dsands843** [comment]
So what do I need to do

**Comment by ilkerccom** [comment]
Hello, fixed. You must restart the app.

**Comment by vitpronchatov** [comment]
I stuck with the same error.
I double checked my settings but I still get this error.
Everything worked perfect in the past but not now.

**Comment by ilkerccom** [comment]
> I stuck with the same error. I double checked my settings but I still get this error. Everything worked perfect in the past but not now.

Hello,

- Check your “user_token” value. Get it from btcpuzzle.info website.
- Check your “wallet_address” value. You must use the btc address you registered with. Get it from btcpuzzle.info website. Check template; “{walletaddress}.{workername} or “{walletaddress}”
- If you requested too many ranges and did not scan, you may have been temporarily banned.
- If the problem is not solved, you can send me your username and I will check it. (Telegram or support@btcpuzzle.info)

Thanks.
